### ISSUE TITLE
What is input_path?

### ISSUE THREAD

**Issue by haydensflee** [kokeshing/WaveNet-tf2#3]
Hi @kokeshing. Thank you for the very cool implementation of wavenet using tf2.
I'm trying to understand how to run your synthesize.py code and I would like to ask what the argument input_path is meant to be?

So output_path is where we want to save our generated data.
weight_path is where we have saved our trained model weights.
What is input_path meant to be and what is its purpose?

Thanks

**Comment by kokeshing** [comment]
This repository is an implementation of WaveNet vocoder.
Vocoder recovers audio waveforms from some acoustic features.

Therefore, input_path of synthesize.py specifies the location of the audio file from which the acoustic features you want vocoder to recover are extracted.
If the model is well trained, the output audio will be almost the same as the input audio.

If you want to do text-to-speech, you need to prepare a model to predict acoustic features from linguistic features.

I recommend checking other recently proposed Neural Vocoders such as [HiFiGAN](https://github.com/jik876/hifi-gan), since this repository was implemented 4 years ago and WaveNet has some problems such as long inference time, 

Best regards
